### PR TITLE
Open undo fixes

### LINKED ISSUE #2122: The newline inserted by 'o' or 'O' should be undone with the text that is inserted
A simple `cw` followed by new text followed by `<Esc>` is undone with a single undo. Similarly, in vim, the newline inserted by a single `o` (insert line below) or `O` (insert line above) is undone when then new text is undone. However, in VsVim, it takes two undo steps to undo one `o`  or `O` command.  The first one undo undoes the insert and the second undo undoes the newline.

### PR DESCRIPTION
**Pull request by ricksladkey**
Changes:

- Create a linked undo for the 'O' (insert line above) and 'o' (insert line below) operations
- Centralize completing an undo transaction during a discarded mode switch
- Add undo tests for 'O' and 'o'

Fixes:

- Fixes #2122

### CODE REVIEW

File: Src/VimCore/CoreInterfaces.fs [hunk 1]
```diff
@@ -2299,6 +2299,22 @@ type ModeArgument =
     /// match to process and the range is the full range to consider for a replace
     | Substitute of SnapshotSpan * SnapshotLineRange * SubstituteData
 
+with
+
+    // Running linked commands will throw away the ModeSwitch value.  This can contain
+    // an open IUndoTransaction.  This must be completed here or it will break undo in the
+    // ITextBuffer
+    member x.CompleteAnyTransaction =
```
Comment (jaredpar) [inline Src/VimCore/CoreInterfaces.fs]: >CompleteAnyTransaction [](start = 13, length = 22)

Ha. I saw this and said "i know i've already defined this method" spent a few minutes looking for that code, found it then saw you'd already also found and refactored that code in this very PR ;)
