### PR TITLE
Mark glyph improvements

### LINKED ISSUE #2402: Argument null on startup
This exception happens on startup on some machines with 2.6.0 installed:

```
System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: source&#x000D;&#x000A;   at
 System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)&#x000D;&#x000A;   at
 System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)&#x000D;&#x000A;   at
 Vim.UI.Wpf.Implementation.MarkGlyph.MarkGlyphTaggerSource.IsMarkHidden(Mark mark)&#x000D;&#x000A;   at
 Vim.UI.Wpf.Implementation.MarkGlyph.MarkGlyphTaggerSource.UpdateMark(Mark mark)&#x000D;&#x000A;   at
 Vim.UI.Wpf.Implementation.MarkGlyph.MarkGlyphTaggerSource.LoadNewBufferMarks()&#x000D;&#x000A;   at
 Vim.UI.Wpf.Implementation.MarkGlyph.MarkGlyphTaggerSource..ctor(IVimBufferData vimBufferData, IMarkDisplayUtil markDisplayUtil)&#x000D;&#x000A;   at
 Vim.UI.Wpf.Implementation.MarkGlyph.MarkGlyphTaggerSourceFactory.CreateMarkGlyphTaggerSource(IVimBufferData vimBufferData)&#x000D;&#x000A;   at
 Vim.UI.Wpf.Implementation.MarkGlyph.MarkGlyphTaggerSourceFactory.&lt;&gt;c__DisplayClass5_0`1.&lt;Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger&gt;b__0()&#x000D;&#x000A;   at
 &lt;StartupCode$Vim-Core&gt;.$FSharpExtensions.ToFSharpFunc@56.Invoke(Unit unitVar0)&#x000D;&#x000A;   at
 Vim.TaggerUtil.createTagger@1230-1.Invoke(Unit unitVar0)&#x000D;&#x000A;   at
 Vim.CountedValue`1.GetOrCreate[a](PropertyCollection propertyCollection, a key, FSharpFunc`2 createFunc)&#x000D;&#x000A;   at
 Vim.CountedTagger`1..ctor(PropertyCollection propertyCollection, Object key, FSharpFunc`2 createFunc)&#x000D;&#x000A;   at
 Vim.TaggerUtil.CreateBasicTagger[TTag](PropertyCollection propertyCollection, Object key, FSharpFunc`2 createFunc)&#x000D;&#x000A;   at
 Vim.UI.Wpf.Implementation.MarkGlyph.MarkGlyphTaggerSourceFactory.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at
 Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at
 Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### LINKED ISSUE #2419: markers margin
I really like the new way to visualize markers - even not knowing enough about the markers to understand all the visualized markers and how to use them efficitently.

Sincerely the drawn markers collide with VS "markers" for breakpoints, bookmarks and tasks:

- breakpoint on VsVim markers
- bookmark on VsVim marker
- task on VsVim marker

Is there a chance to make it a bit "cleaner"?

Thanks in advance!

### LINKED ISSUE #2425: What the setting Hide Marks Value
I want hide marks on margin.
But i don't know the setting's value
In new version, I want have some prompt
Thanks

### PR DESCRIPTION
**Pull request by ricksladkey**
#### Issues

- Fixes #2402
- Closes #2419
- Closes #2425

#### Changes

- Fixes a null-reference exception if `MarkDisplayUtil` is accessed before it is synced with the setting
- Fixes hiding or unhiding marks while the editor is running
- Moves mark glyphs behind other glyphs (e.g., breakpoints) in the indicator margin
- Adds the capability to express a range of marks to hide, e.g. `a-z` to hide all lettered local marks
- Adds the capability to easily hide all marks using `:set vsvim_hidemarks=-`

### CODE REVIEW

File: Src/VimWpf/Implementation/MarkGlyph/MarkGlyphTaggerSource.cs [hunk 1]
```diff
@@ -119,10 +119,40 @@ private void OnTextBufferChanged(object sender, TextContentChangedEventArgs e)
 
         private void OnHideMarksChanged(object sender, EventArgs e)
         {
-            _hideMarks = _markDisplayUtil.HideMarks;
+            _hideMarks = ExpandHideMarksSetting(_markDisplayUtil.HideMarks);
             UpdateAllMarks();
         }
 
+        HashSet<char> ExpandHideMarksSetting(string setting)
```
Comment (jaredpar) [inline Src/VimWpf/Implementation/MarkGlyph/MarkGlyphTaggerSource.cs]: Can be static.

File: Src/VimWpf/Implementation/MarkGlyph/MarkGlyphTaggerSource.cs [hunk 2]
```diff
@@ -119,10 +119,40 @@ private void OnTextBufferChanged(object sender, TextContentChangedEventArgs e)
...
+            }
+            var i = 0;
+            while (i < setting.Length)
+            {
+                var c1 = setting[i];
+                if (i + 2 < setting.Length && setting[i + 1] == '-')
+                {
+                    // Expand range, e.g. 'a-z'.
+                    var c2 = setting[i + 2];
+                    for (var c = c1; c <= c2; c++)
```
Comment (jaredpar) [inline Src/VimWpf/Implementation/MarkGlyph/MarkGlyphTaggerSource.cs]: If the user enters "z-a" we won't add z, - or a to the hide list.

Comment (ricksladkey) [reply Src/VimWpf/Implementation/MarkGlyph/MarkGlyphTaggerSource.cs]: We now allow a range to be specified in either order.
