### PR TITLE
Make session data reversible for macro registers

### LINKED ISSUE #2214: Macros containing special keys are not reloaded properly
If a macro is recorded using a special key (e.g. `<Left>`), and Visual Studio is then exited and restarted, the macro will not work properly. The session data serialization file format does not distinguish macro registers from string registers, and cannot faithfully encode the contents of macro registers containing special keys.

### PR DESCRIPTION
**Pull request by ricksladkey**
Fixes #2214

### CODE REVIEW

File: Src/VimCore/Vim.fs [hunk 1]
```diff
@@ -784,13 +791,23 @@ type internal Vim
             _ as ex -> VimTrace.TraceError ex
 
     member x.LoadSessionDataCore filePath =
-        let sessionData = x.ReadSessionData (x.GetSessionDataFilePath())
+        let sessionData = x.ReadSessionData filePath
```
Comment (jaredpar) [inline Src/VimCore/Vim.fs]: Nice catch.
