### PR TITLE
fixes for one-commmand mode switching and display

### LINKED ISSUE #2346: One-command mode issues
A number of mode switch sequences involving "one-command" operations do not match gVim 8.0 behavior.  Some modes are simply misreported in the status area (e.g. (insert) VISUAL might be shown as VISUAL).  A number of these sequences actually enter an unexpected or invalid state.  

_Note: the following test cases all start in normal mode_

Sequence | Expected | Actual
--- | --- | ---
`gh<C-o>:<C-u>pwd<CR>` | NORMAL | SELECT
`gh<C-o>:<Esc>` | NORMAL | SELECT
`i<C-o>:<Esc>` | INSERT | (insert)
`i<C-o>R<Esc>` | NORMAL | (insert)
`i<C-o>gh<C-o>:<Esc>` | INSERT | SELECT
`i<C-o>gh<C-o>:<C-u>pwd<CR>` | INSERT | SELECT
`i<C-o>gh<C-o><Esc>` | INSERT | SELECT
`i<C-o>gh<C-o>w` | (insert) SELECT | SELECT
`i<C-o>ghx` | INSERT | ? (need 3 `<Esc>` to return to NORMAL)
`i<C-o>i<Esc>` | NORMAL | (insert)
`i<C-o>v:<Esc>` | INSERT | (insert)

### PR DESCRIPTION
**Pull request by dhmgit**
Fixes #2346 

This is the most "invasive" change I've made so far in this codebase, so I expect a fair amount of scrutiny.  The biggest challenge is to deal with the very large number of code paths that can lead to a mode switch without resorting to adding a lot of special case logic, or modifying the mode-specific code.  The more I experimented with gVim, the more I was surprised by features (or "features") that I didn't know existed.  Hopefully, I've hit all or nearly all of them.

### CODE REVIEW

File: Src/VimCore/VimBuffer.fs [hunk 1]
```diff
@@ -190,6 +190,7 @@ type internal VimBuffer
     let _keyMap = _vim.KeyMap
     let mutable _processingInputCount = 0
     let mutable _isClosed = false
+    let mutable _inSelectModeOneCommand = false
```
Comment (jaredpar) [inline Src/VimCore/VimBuffer.fs]: Believe this state should be in `IVimTextBuffer` now. This would line up better with recent changes.

File: Src/VimCore/VimBuffer.fs [hunk 2]
```diff
@@ -682,12 +688,43 @@ type internal VimBuffer
...
+                | Some oneTimeModeKind ->
+                    _inSelectModeOneCommand <- false
+                    _vimTextBuffer.InOneTimeCommand <- None
+                    oneTimeModeKind
+                | None ->
+                    modeKind
+            else
+                modeKind
+        
+        _modeMap.SwitchMode overrideModeKind modeArgument
```
Comment (jaredpar) [inline Src/VimCore/VimBuffer.fs]: This logic feels like it's in the wrong place. The implementation of `SwitchMode` should be pretty much what it is today: switch to the mode that is provided. Logic around taking a desired mode and changing it based on the current state should be at a higher layer.

Comment (dhmgit) [reply Src/VimCore/VimBuffer.fs]: At some point, I think I became overly concerned about missing a case without centralizing the switching override logic.  It turned out to be quite easy to move most of the logic back to VimBuffer.ProcessOneKeyInput where it originally resided, especially with the added test net.  Only one special case was needed in SelectionChangeTracker.  This seems like the best compromise because moving all of the mode switch logic to mode-specific layers would involve touching somewhere north of 200 locations that return ModeSwitch results.

How do you feel about the one-time command logic added to SwitchPreviousMode?  Removing this logic would mean duplicating it in both VimBuffer as well as VimInterpreter.RunNormal.  My testing indicates that running a "norm" command from one-command mode switches back to the saved mode (and not to command mode, which is technically the previous mode).
